#!/usr/bin/bash

VALUE=$1

if [[ -d $VALUE ]]; then
    echo "$VALUE is a directory"
    TIME=$(date +%Y%m%d_%H%M%S)
    FILE_NAME="logs_archive_$TIME.tar.gz"
    echo "Creating archive: $FILE_NAME"
    tar cfzv "$FILE_NAME" "$VALUE"
elif [[ -f $VALUE ]]; then
    echo "$VALUE is a file"
else
    echo "$VALUE is not valid"
fi

